name: Monitor ALEGO Diário
on:
  schedule:
    - cron: '*/30 * * * *' # Roda a cada 30 minutos
  workflow_dispatch: # Permite que você rode manualmente para testar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar bibliotecas
        run: pip install requests beautifulsoup4
      - name: Executar Monitor
        env:
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          ID_TELEGRAM: ${{ secrets.ID_TELEGRAM }}
        run: python monitor.py
      - name: Salvar progresso
        run: |
          git config --global user.name 'Bot Monitor'
          git config --global user.email 'bot@monitor.com'
          git add ultimo_visto.txt
          git commit -m "Atualizando ultima postagem" || exit 0
          git push
